# Generated by tools/build_ch02.py; JA SHA256 fa06b84c2245e33152c419fa7fc3abf503dc6ca34fde0aa2f9403a7f53730e0a
# ZH SHA256 bbaf5c62ea7d38647accaf1bc5308ecd390da01763d31cea280a8acd8447c52e
# Approved visual staging and audio; supplied voices are optional.
label ch02_sc01:
    $ ch02_audio_scene("ch02_sc01")

    # ch02_sc01_dir001
    window hide None
    scene ch02_bg living
    with dissolve
    show ch02_qixing indoor at ch_left
    show ch02_chinatsu indoor at ch02_indoor_seated
    with dissolve
    $ ch02_audio("room")
    $ ch02_audio("tv")

    # ch02_sc01_001
    window show None
    $ ch_line_id = "ch02_sc01_001"
    $ ch_voice(None, "ch02_sc01_001")
    ch_thought "……一大清早，这钢琴倒是弹得精神十足。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}……朝から、ずいぶん元気なピアノだな。{/font}{/color}{/size}") id ch02_sc01_001

    # ch02_sc01_002
    window show None
    $ ch_line_id = "ch02_sc01_002"
    $ ch_voice(None, "ch02_sc01_002")
    ch_thought "平平安安地过了一夜。才刚为这件事松了口气，就又被电视吵醒了。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}何事もなく、一晩が過ぎた。それだけで少しほっとしたのに、今度はテレビに起こされた。{/font}{/color}{/size}") id ch02_sc01_002

    # ch02_sc01_dir002
    window hide None
    scene ch02_cg television
    with dissolve

    # ch02_sc01_003
    window show None
    $ ch_line_id = "ch02_sc01_003"
    $ ch_voice('chinatsu', "ch02_sc01_003")
    ch_chinatsu "……是我爸爸。我从早上开始，就一直在看这个。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}……お父さん。朝からずっと、これを見てたんです。{/font}{/color}{/size}") id ch02_sc01_003

    # ch02_sc01_004
    window show None
    $ ch_line_id = "ch02_sc01_004"
    $ ch_voice('chinatsu', "ch02_sc01_004")
    ch_chinatsu "毕竟练习了二十年半。也算是达到了艺术的‘巅峰’吧。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}練習歴二十年半ですから。芸術の『極み』に達した、ってところでしょうか。{/font}{/color}{/size}") id ch02_sc01_004

    # ch02_sc01_005
    window hide None
    scene ch02_bg living
    with dissolve
    show ch02_qixing indoor at ch_left
    show ch02_chinatsu indoor_wry at ch02_indoor_seated
    with dissolve
    window show None
    $ ch_line_id = "ch02_sc01_005"
    $ ch_voice(None, "ch02_sc01_005")
    ch_qixing "你是我的。我又是你的……什么呢。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}君は俺のもの。俺は君の、何なんだ……。{/font}{/color}{/size}") id ch02_sc01_005

    # ch02_sc01_006
    show ch02_chinatsu indoor_surprised at ch02_indoor_seated
    with Dissolve(0.2)
    window show None
    $ ch_line_id = "ch02_sc01_006"
    $ ch_voice('chinatsu', "ch02_sc01_006")
    ch_chinatsu "咦，您知道这首歌吗？就是让我爸爸成名的那首。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}あれ、その歌、知ってるんですか？　父が有名になった曲。{/font}{/color}{/size}") id ch02_sc01_006

    # ch02_sc01_dir003
    show ch02_qixing indoor_bemused at ch_left
    with Dissolve(0.2)

    # ch02_sc01_007
    window show None
    $ ch_line_id = "ch02_sc01_007"
    $ ch_voice(None, "ch02_sc01_007")
    ch_qixing "靠那一首歌走红，后来又转行当了钢琴家。梅川备代的事，城里谁不知道啊。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}あの一曲で売れて、それからピアニストに転向。{rb}梅川備代{/rb}{rt}サスペンダーなし{/rt}の話なら、街じゅう知ってるよ。{/font}{/color}{/size}") id ch02_sc01_007

    # ch02_sc01_008
    window show None
    $ ch_line_id = "ch02_sc01_008"
    $ ch_voice(None, "ch02_sc01_008")
    ch_qixing "说不定，还得多亏各位‘全民制作人’呢。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}『国民プロデューサー』の皆さんの、おかげなのかもな。{/font}{/color}{/size}") id ch02_sc01_008

    # ch02_sc01_009
    window show None
    $ ch_line_id = "ch02_sc01_009"
    $ ch_voice(None, "ch02_sc01_009")
    ch_qixing "那我去买早饭了。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}じゃ、朝飯を買ってくる。{/font}{/color}{/size}") id ch02_sc01_009

    # ch02_sc01_dir004
    window hide None
    $ ch02_audio_stop("ch_diegetic", 0.35)
    $ ch02_audio_stop("ch_ambience", 0.35)
    scene black
    $ ch02_audio("door_close")
    with Dissolve(0.35)
    pause 0.5
    window hide None
    scene ch02_bg street_posted
    with dissolve
    show ch_qixing neutral at ch_left
    with dissolve
    $ ch_audio("daily")
    $ ch_audio("street_room")

    # ch02_sc01_010
    window show None
    $ ch_line_id = "ch02_sc01_010"
    $ ch_voice(None, "ch02_sc01_010")
    ch_thought "……千夏？这里也有，那边也有。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}……千夏？　こんなところにも、あっちにも。{/font}{/color}{/size}") id ch02_sc01_010

    # ch02_sc01_011
    show ch02_notice
    with dissolve
    window show None
    $ ch_line_id = "ch02_sc01_011"
    $ ch_voice(None, "ch02_sc01_011")
    ch02_notice "小女梅川千夏失踪至今，已有两周半。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}娘の{rb}梅川千夏{/rb}{rt}うめかわちなつ{/rt}が行方不明になって、二週間半になります。{/font}{/color}{/size}") id ch02_sc01_011

    # ch02_sc01_012
    window show None
    $ ch_line_id = "ch02_sc01_012"
    $ ch_voice(None, "ch02_sc01_012")
    ch02_notice "失踪当天，小女未系背带，发型也并非中分。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}いなくなった日、娘はサスペンダーを着けておらず、髪もセンター分けではありませんでした。{/font}{/color}{/size}") id ch02_sc01_012

    # ch02_sc01_013
    window show None
    $ ch_line_id = "ch02_sc01_013"
    $ ch_voice(None, "ch02_sc01_013")
    ch02_notice "只因那孩子太过美丽。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}{rb}只因{/rb}{rt}ただ{/rt}、あの子が美しすぎたから。{/font}{/color}{/size}") id ch02_sc01_013

    # ch02_sc01_014
    window show None
    $ ch_line_id = "ch02_sc01_014"
    $ ch_voice(None, "ch02_sc01_014")
    ch02_notice "——梅川备代" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}――{rb}梅川備代{/rb}{rt}サスペンダーなし{/rt}{/font}{/color}{/size}") id ch02_sc01_014

    # ch02_sc01_015
    window show None
    $ ch_line_id = "ch02_sc01_015"
    $ ch_voice(None, "ch02_sc01_015")
    ch_thought "……这真的是打算找人，对吧。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}……人を捜す気はあるんだよな、これ。{/font}{/color}{/size}") id ch02_sc01_015

    # ch02_sc01_dir005
    window hide None
    hide ch02_notice
    show screen ch_phone("馬皙", incoming=True)
    with dissolve
    $ ch02_audio("phone_ring")
    pause

    # ch02_sc01_016
    $ ch02_audio_stop("sound", 0)
    show screen ch_phone("馬皙", mode="call")
    window show None
    $ ch_line_id = "ch02_sc01_016"
    $ ch_voice('maxi', "ch02_sc01_016")
    ch_maxi "喂，徐启星！音乐会的票，我弄到手了！" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}おう、{rb}徐启星{/rb}{rt}シュー・チーシン{/rt}！　コンサートのチケット、手に入ったぞ。{/font}{/color}{/size}") id ch02_sc01_016

    # ch02_sc01_017
    window show None
    $ ch_line_id = "ch02_sc01_017"
    $ ch_voice('maxi', "ch02_sc01_017")
    ch_maxi "后天下午两点半，艾昆剧院。一定要来啊！" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}明後日、午後二時半。{rb}艾昆{/rb}{rt}アイクン{/rt}劇場な。絶対来いよ！{/font}{/color}{/size}") id ch02_sc01_017

    # ch02_sc01_dir006
    hide screen ch_phone
    with dissolve
    pause 0.3

    # ch02_sc01_018
    window show None
    $ ch_line_id = "ch02_sc01_018"
    $ ch_voice(None, "ch02_sc01_018")
    ch_thought "……好歹让我回句话啊。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}……返事ぐらい、させろよ。{/font}{/color}{/size}") id ch02_sc01_018

    return
