# Generated by tools/build_ch02.py; JA SHA256 fa06b84c2245e33152c419fa7fc3abf503dc6ca34fde0aa2f9403a7f53730e0a
# ZH SHA256 bbaf5c62ea7d38647accaf1bc5308ecd390da01763d31cea280a8acd8447c52e
# Approved visual staging and audio; supplied voices are optional.
label ch02_sc02:
    $ ch02_audio_scene("ch02_sc02")

    # ch02_sc02_dir001
    window hide None
    scene black
    with Dissolve(0.3)
    $ ch02_audio("door_open")
    pause 1.4
    window hide None
    scene ch02_bg entry_shoes
    $ ch02_audio("room")
    $ ch02_audio("tv_return")
    with dissolve
    pause 1.0
    window hide None
    scene ch02_bg living
    with dissolve
    show ch02_qixing indoor_concerned at ch_left
    show ch02_chinatsu indoor at ch02_indoor_seated
    with dissolve

    # ch02_sc02_001
    window show None
    $ ch_line_id = "ch02_sc02_001"
    $ ch_voice(None, "ch02_sc02_001")
    ch_thought "还在看。有那么在意吗。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}まだ、見てる。そんなに気になるのか。{/font}{/color}{/size}") id ch02_sc02_001

    # ch02_sc02_dir002
    window hide None
    scene ch02_cg chinatsu_bruise_detail_v3
    with dissolve

    # ch02_sc02_002
    window show None
    $ ch_line_id = "ch02_sc02_002"
    $ ch_voice(None, "ch02_sc02_002")
    ch_thought "左臂上的淤青。……还是这么明显。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}左腕の、あざ。……まだ、こんなにはっきり。{/font}{/color}{/size}") id ch02_sc02_002

    # ch02_sc02_003
    window show None
    $ ch_line_id = "ch02_sc02_003"
    $ ch_voice(None, "ch02_sc02_003")
    ch_thought "要说只是不小心撞到了哪里，这也……" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}どこかにぶつけただけ、にしては……。{/font}{/color}{/size}") id ch02_sc02_003

    # ch02_sc02_dir003
    window hide None
    scene ch02_cg qixing_take_hand_v6
    with dissolve
    pause 0.65
    window hide None
    $ ch02_audio("sleeve")
    scene ch02_cg chinatsu_withdraw_hand_v1
    with dissolve

    # ch02_sc02_004
    window show None
    $ ch_line_id = "ch02_sc02_004"
    $ ch_voice(None, "ch02_sc02_004")
    ch_thought "糟了。一不留神，老毛病又犯了。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}しまった。つい、いつもの癖で。{/font}{/color}{/size}") id ch02_sc02_004

    # ch02_sc02_005
    window show None
    $ ch_line_id = "ch02_sc02_005"
    $ ch_voice(None, "ch02_sc02_005")
    ch_qixing "千夏，你那块淤青……" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}千夏。その、あざは……。{/font}{/color}{/size}") id ch02_sc02_005

    # ch02_sc02_006
    window show None
    $ ch_line_id = "ch02_sc02_006"
    $ ch_voice('chinatsu', "ch02_sc02_006")
    ch_chinatsu "……别问了。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}……聞かないで。{/font}{/color}{/size}") id ch02_sc02_006

    # ch02_sc02_dir004
    $ ch02_audio_end()
    window hide None
    scene black
    with fade

    return
