# Generated by tools/build_ch02.py; JA SHA256 fa06b84c2245e33152c419fa7fc3abf503dc6ca34fde0aa2f9403a7f53730e0a
# ZH SHA256 bbaf5c62ea7d38647accaf1bc5308ecd390da01763d31cea280a8acd8447c52e
# Approved visual staging and audio; supplied voices are optional.
label ch02_sc03:
    $ ch02_audio_scene("ch02_sc03")

    # ch02_sc03_dir001
    call ch_card("ch02_morning") from ch02_morning_return
    window hide None
    scene ch02_bg street_removed
    with dissolve
    show ch_qixing neutral at ch_left
    with dissolve
    $ ch_audio("daily")
    $ ch_audio("street_room")

    # ch02_sc03_001
    window show None
    $ ch_line_id = "ch02_sc03_001"
    $ ch_voice(None, "ch02_sc03_001")
    ch_thought "这两天，千夏一直闷闷不乐。果然，是我碰到了她不想提的事吗。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}この二日、千夏はずっと沈んだままだ。やっぱり、触れてほしくないことだったんだろうか。{/font}{/color}{/size}") id ch02_sc03_001

    # ch02_sc03_002
    window show None
    $ ch_line_id = "ch02_sc03_002"
    $ ch_voice(None, "ch02_sc03_002")
    ch_thought "之前贴得到处都是的纸，也全没了。是妨碍市容，被管理人员撕掉了吗？" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}あれだけ貼ってあった紙も、すっかりなくなってる。邪魔だって、市の取り締まりで剥がされたのか？{/font}{/color}{/size}") id ch02_sc03_002

    # ch02_sc03_dir002
    show screen ch_phone("馬皙", mode="notification")
    with dissolve
    $ ch02_audio("notification")

    # ch02_sc03_003
    window show None
    $ ch_line_id = "ch02_sc03_003"
    $ ch_voice(None, "ch02_sc03_003")
    ch_thought "马皙发来的。音乐会别迟到……啊。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}馬皙からだ。コンサート、遅れるなよ……か。{/font}{/color}{/size}") id ch02_sc03_003

    # ch02_sc03_004
    window show None
    $ ch_line_id = "ch02_sc03_004"
    $ ch_voice(None, "ch02_sc03_004")
    ch_thought "让千夏一个人看家，自己跑去听音乐会，总觉得不太好。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}千夏を一人で留守番させて、俺だけ聴きに行くのもな。{/font}{/color}{/size}") id ch02_sc03_004

    # ch02_sc03_dir003
    hide screen ch_phone
    $ ch02_audio_stop("music", 0.3)
    $ ch02_audio_stop("ch_ambience", 0.3)
    window hide None
    scene black
    with Dissolve(0.3)
    $ ch02_audio("door_open")
    pause 1.4
    hide screen ch_phone
    window hide None
    scene ch02_bg entry
    with dissolve
    $ ch02_audio("room")

    # ch02_sc03_005
    window show None
    $ ch_line_id = "ch02_sc03_005"
    $ ch_voice(None, "ch02_sc03_005")
    ch_qixing "……千夏？" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}……千夏？{/font}{/color}{/size}") id ch02_sc03_005

    # ch02_sc03_006
    window show None
    $ ch_line_id = "ch02_sc03_006"
    $ ch_voice(None, "ch02_sc03_006")
    ch_thought "鞋子，不见了。房间里也——没人。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}靴が、ない。部屋にも――いない。{/font}{/color}{/size}") id ch02_sc03_006

    # ch02_sc03_dir004
    window hide None
    scene ch02_bg street_removed
    with dissolve
    pause 0.8
    window hide None
    scene ch02_bg living
    with dissolve
    $ ch02_audio("mystery_low")

    # ch02_sc03_007
    window show None
    $ ch_line_id = "ch02_sc03_007"
    $ ch_voice(None, "ch02_sc03_007")
    ch_thought "今早，那些消失的寻人启事。……难道。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}今朝、消えていた張り紙。……まさか。{/font}{/color}{/size}") id ch02_sc03_007

    # ch02_sc03_008
    window show None
    $ ch_line_id = "ch02_sc03_008"
    $ ch_voice(None, "ch02_sc03_008")
    ch_thought "冷静。碰到这种情况该怎么做，训练时不是已经反复练过了吗。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}落ち着け。こういうときに何をするか。訓練で、何度も叩き込まれただろ。{/font}{/color}{/size}") id ch02_sc03_008

    # ch02_sc03_009
    window show None
    $ ch_line_id = "ch02_sc03_009"
    $ ch_voice(None, "ch02_sc03_009")
    ch_thought "遇到她的时候，假期就只剩两天了。本来想着明天回去上班，再找人商量一下她的事。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}休暇もあと二日、ってところで出会った子だ。明日、仕事に戻ったら、あの子のことも相談しようと思っていた。{/font}{/color}{/size}") id ch02_sc03_009

    # ch02_sc03_010
    window show None
    $ ch_line_id = "ch02_sc03_010"
    $ ch_voice(None, "ch02_sc03_010")
    ch_thought "离音乐会还有六个小时。……已经不能再等到明天了。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}コンサートまでは、まだ六時間ある。……もう、明日まで待ってはいられない。{/font}{/color}{/size}") id ch02_sc03_010

    # ch02_sc03_dir005
    $ ch02_audio("door_close")
    window hide None
    scene black
    with fade
    $ ch02_audio_stop("ch_ambience")

    return
