# Generated by tools/build_ch02.py; JA SHA256 fa06b84c2245e33152c419fa7fc3abf503dc6ca34fde0aa2f9403a7f53730e0a
# ZH SHA256 bbaf5c62ea7d38647accaf1bc5308ecd390da01763d31cea280a8acd8447c52e
# Approved visual staging and audio; supplied voices are optional.
label ch02_sc04:
    $ ch02_audio_scene("ch02_sc04")

    # ch02_sc04_dir001
    window hide None
    scene black
    with Dissolve(0.3)
    $ ch02_audio("door_open")
    pause 1.4
    window hide None
    scene ch02_bg office
    with dissolve
    show ch_qixing neutral at ch_left
    show ch02_wengang work at ch02_colleague_right
    with dissolve
    $ ch02_audio("mystery_low")
    $ ch02_audio("office")

    # ch02_sc04_001
    window show None
    $ ch_line_id = "ch02_sc04_001"
    $ ch_voice('wengang', "ch02_sc04_001")
    ch02_wengang "哟，休假结束了？今天就上班？" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}お、休暇は終わりか？　今日から出勤？{/font}{/color}{/size}") id ch02_sc04_001

    # ch02_sc04_002
    window show None
    $ ch_line_id = "ch02_sc04_002"
    $ ch_voice(None, "ch02_sc04_002")
    ch_thought "是我的同事，文钢。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}同僚の{rb}文鋼{/rb}{rt}ウェン・ガン{/rt}だ。{/font}{/color}{/size}") id ch02_sc04_002

    # ch02_sc04_003
    window show None
    $ ch_line_id = "ch02_sc04_003"
    $ ch_voice(None, "ch02_sc04_003")
    ch_qixing "没，明天才上班。今天闲着没事，就想过来做点准备。……局长也来了？" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}いや、明日から。今日は暇だから、少し準備をしようと思って。……局長も来てる？{/font}{/color}{/size}") id ch02_sc04_003

    # ch02_sc04_dir002
    pass

    # ch02_sc04_004
    window show None
    $ ch_line_id = "ch02_sc04_004"
    $ ch_voice(None, "ch02_sc04_004")
    ch_qixing "还有……有件事想跟你商量。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}それと……ちょっと、相談がある。{/font}{/color}{/size}") id ch02_sc04_004

    # ch02_sc04_dir003
    window hide None
    scene black
    with dissolve
    pause 0.3
    window hide None
    scene ch02_bg office
    with dissolve
    show ch_qixing serious at ch_left
    show ch02_wengang work_indignant at ch02_colleague_right
    with dissolve

    # ch02_sc04_005
    window show None
    $ ch_line_id = "ch02_sc04_005"
    $ ch_voice('wengang', "ch02_sc04_005")
    ch02_wengang "这叫什么事啊！现在的孩子，好歹也该懂点怎么保护自己吧……" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}何だよそれ！　今どきの子は、もう少し自分の身を守るってことをだな……。{/font}{/color}{/size}") id ch02_sc04_005

    # ch02_sc04_006
    window show None
    $ ch_line_id = "ch02_sc04_006"
    $ ch_voice('wengang', "ch02_sc04_006")
    ch02_wengang "跑到不认识的男人家里，还住了两天？两天啊！" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}知らない男の家に転がり込んで、二日も泊まった？　二日だぞ？{/font}{/color}{/size}") id ch02_sc04_006

    # ch02_sc04_007
    hide ch_qixing
    show ch02_qixing casual_anger at ch_left
    with Dissolve(0.2)
    window show None
    $ ch_line_id = "ch02_sc04_007"
    $ ch_voice(None, "ch02_sc04_007")
    ch_thought "这种时候，你在意的居然是这个。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}そこかよ。今、引っかかるのは。{/font}{/color}{/size}") id ch02_sc04_007

    # ch02_sc04_008
    window show None
    $ ch_line_id = "ch02_sc04_008"
    $ ch_voice(None, "ch02_sc04_008")
    ch_qixing "……所以，你觉得该怎么办。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}……それで、どうすればいいと思う。{/font}{/color}{/size}") id ch02_sc04_008

    # ch02_sc04_009
    show ch02_wengang work_skeptical at ch02_colleague_right
    with Dissolve(0.2)
    window show None
    $ ch_line_id = "ch02_sc04_009"
    $ ch_voice('wengang', "ch02_sc04_009")
    ch02_wengang "还能怎么办。寻人启事都没了，应该是家里人来接走了吧。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}どうもこうも。張り紙がなくなったなら、家の人が迎えに来たんだろ。{/font}{/color}{/size}") id ch02_sc04_009

    # ch02_sc04_010
    window show None
    $ ch_line_id = "ch02_sc04_010"
    $ ch_voice('wengang', "ch02_sc04_010")
    ch02_wengang "你去跟局长说，搞不好挨训的反而是你。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}局長に話したら、お前のほうが説教されかねないぞ。{/font}{/color}{/size}") id ch02_sc04_010

    # ch02_sc04_011
    window show None
    $ ch_line_id = "ch02_sc04_011"
    $ ch_voice('wengang', "ch02_sc04_011")
    ch02_wengang "就算她真的失踪了，你能把她的特征说清楚吗？连真名都还没弄明白吧。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}仮に本当に行方不明だとしても、詳しい特徴を説明できるのか？　本名だって、はっきりしないんだろ。{/font}{/color}{/size}") id ch02_sc04_011

    # ch02_sc04_dir004
    $ ch02_audio("paper")
    window hide None
    scene ch02_cg qixing_files_detail_v1
    with dissolve

    # ch02_sc04_012
    window show None
    $ ch_line_id = "ch02_sc04_012"
    $ ch_voice(None, "ch02_sc04_012")
    ch_thought "我懂他的意思。懂归懂……可就是来气。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}言いたいことは分かる。分かるけど……腹が立つ。{/font}{/color}{/size}") id ch02_sc04_012

    # ch02_sc04_013
    window show None
    $ ch_line_id = "ch02_sc04_013"
    $ ch_voice(None, "ch02_sc04_013")
    ch_thought "只能自己想办法了吗。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}自分で、どうにかするしかないのか。{/font}{/color}{/size}") id ch02_sc04_013

    # ch02_sc04_dir005
    window hide None
    pause 0.3

    # ch02_sc04_014
    window show None
    $ ch_line_id = "ch02_sc04_014"
    $ ch_voice(None, "ch02_sc04_014")
    ch_qixing "……可恶！" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}……くそっ！{/font}{/color}{/size}") id ch02_sc04_014

    # ch02_sc04_dir006
    $ ch02_audio("door_close")
    window hide None
    scene ch02_bg office
    show ch02_wengang work_surprised at ch02_colleague_right
    with None
    pause 1.5
    scene black
    with fade
    $ ch02_audio_end()

    return
