# Generated by tools/build_ch02.py; JA SHA256 fa06b84c2245e33152c419fa7fc3abf503dc6ca34fde0aa2f9403a7f53730e0a
# ZH SHA256 bbaf5c62ea7d38647accaf1bc5308ecd390da01763d31cea280a8acd8447c52e
# Approved visual staging and audio; supplied voices are optional.
label ch02_sc05:
    $ ch02_audio_scene("ch02_sc05")

    # ch02_sc05_dir001
    window hide None
    scene ch02_bg theatre_exterior
    with fade
    show ch_qixing troubled at ch_left
    show ch_maxi concerned at ch_maxi_position(1690)
    with dissolve
    $ ch_audio("street_room")

    # ch02_sc05_001
    window show None
    $ ch_line_id = "ch02_sc05_001"
    $ ch_voice(None, "ch02_sc05_001")
    ch_thought "下午两点。约好的地方，艾昆剧院。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}午後二時。約束の、艾昆劇場。{/font}{/color}{/size}") id ch02_sc05_001

    # ch02_sc05_002
    window show None
    $ ch_line_id = "ch02_sc05_002"
    $ ch_voice('maxi', "ch02_sc05_002")
    ch_maxi "脸色这么难看。出什么事了？" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}ひどい顔だな。何かあったのか？{/font}{/color}{/size}") id ch02_sc05_002

    # ch02_sc05_003
    window show None
    $ ch_line_id = "ch02_sc05_003"
    $ ch_voice('maxi', "ch02_sc05_003")
    ch_maxi "好了，先别想那么多。听听音乐，总能舒坦一点的。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}まあ、いいから。音楽でも聴けば、少しは気が晴れるって。{/font}{/color}{/size}") id ch02_sc05_003

    # ch02_sc05_dir002
    $ ch02_audio_stop("music")
    $ ch02_audio_stop("ch_ambience")
    window hide None
    scene ch02_bg theatre_performance
    with dissolve
    $ ch02_audio("ensemble")

    # ch02_sc05_004
    window show None
    $ ch_line_id = "ch02_sc05_004"
    $ ch_voice(None, "ch02_sc05_004")
    ch_thought "真气派的音乐厅。连身体都能感到乐声的震动。……可心里还是一点也静不下来。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}立派なホールだ。音も、身体に響く。……なのに、ちっとも落ち着かない。{/font}{/color}{/size}") id ch02_sc05_004

    # ch02_sc05_005
    window show None
    $ ch_line_id = "ch02_sc05_005"
    $ ch_voice(None, "ch02_sc05_005")
    ch_thought "突然出现，又突然消失。明明只相处了短短两天。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}突然現れて、突然いなくなった。たった二日、一緒にいただけなのに。{/font}{/color}{/size}") id ch02_sc05_005

    # ch02_sc05_dir003
    pass

    # ch02_sc05_006
    window show None
    $ ch_line_id = "ch02_sc05_006"
    $ ch_voice(None, "ch02_sc05_006")
    ch_thought "她会不会就在上面。像什么都没发生过一样，拉着小提琴……" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}あそこにいたり、しないだろうか。何もなかったみたいに、ヴァイオリンを弾いて……。{/font}{/color}{/size}") id ch02_sc05_006

    # ch02_sc05_007
    window show None
    $ ch_line_id = "ch02_sc05_007"
    $ ch_voice(None, "ch02_sc05_007")
    ch_thought "……没有。不管找多少遍，都没有。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}……いない。何度探したって、いない。{/font}{/color}{/size}") id ch02_sc05_007

    # ch02_sc05_dir004
    $ ch02_audio_stop("ch_diegetic", 1.2)
    window hide None
    scene ch02_bg theatre_intermission
    with dissolve
    show ch02_theatre_staff apologetic at ch02_service_right
    with dissolve
    $ ch02_audio("audience")

    # ch02_sc05_008
    window show None
    $ ch_line_id = "ch02_sc05_008"
    $ ch_voice('theatre_staff', "ch02_sc05_008")
    ch02_theatre_staff "非常抱歉，今天的首席小提琴手未能出席……" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}申し訳ございません。本日は、首席ヴァイオリン奏者が出演できず……。{/font}{/color}{/size}") id ch02_sc05_008

    # ch02_sc05_009
    window show None
    $ ch_line_id = "ch02_sc05_009"
    $ ch_voice('theatre_staff', "ch02_sc05_009")
    ch02_theatre_staff "为表歉意，我们为各位准备了免费兑换券。凭券可兑换本剧院任意一场演出的门票一张。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}お詫びとして、無料の引換券をお配りしております。当劇場のお好きな公演のチケット一枚と交換いただけます。{/font}{/color}{/size}") id ch02_sc05_009

    # ch02_sc05_dir005
    window hide None
    scene ch02_cg voucher
    with dissolve

    # ch02_sc05_010
    window show None
    $ ch_line_id = "ch02_sc05_010"
    $ ch_voice(None, "ch02_sc05_010")
    ch_thought "首席……小提琴手。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}首席……ヴァイオリン奏者。{/font}{/color}{/size}") id ch02_sc05_010

    # ch02_sc05_011
    window show None
    $ ch_line_id = "ch02_sc05_011"
    $ ch_voice(None, "ch02_sc05_011")
    ch_qixing "喂，那个首席，到底是谁？" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}なあ。その首席って、誰なんだ？{/font}{/color}{/size}") id ch02_sc05_011

    # ch02_sc05_dir006
    window hide None
    scene ch02_bg theatre_side
    with dissolve
    show ch_qixing surprised at ch_left
    show ch02_maxi incredulous at ch_maxi_position(1690)
    with dissolve

    # ch02_sc05_012
    window show None
    $ ch_line_id = "ch02_sc05_012"
    $ ch_voice('maxi', "ch02_sc05_012")
    ch_maxi "你连这个都不知道啊。就是音乐世家梅川家的千金，梅川千夏啊。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}そこから知らないのかよ。音楽の名門、{rb}梅川{/rb}{rt}うめかわ{/rt}家のお嬢さん。{rb}梅川千夏{/rb}{rt}うめかわちなつ{/rt}だって。{/font}{/color}{/size}") id ch02_sc05_012

    # ch02_sc05_013
    window show None
    $ ch_line_id = "ch02_sc05_013"
    $ ch_voice(None, "ch02_sc05_013")
    ch_thought "千夏，是首席……？" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}千夏が、首席……？{/font}{/color}{/size}") id ch02_sc05_013

    # ch02_sc05_014
    window show None
    $ ch_line_id = "ch02_sc05_014"
    $ ch_voice(None, "ch02_sc05_014")
    ch_thought "可她今天没来。那是不是说，她还没回家——" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}その千夏が、今日は来ていない。だったら、まだ家に帰っていないんじゃ――。{/font}{/color}{/size}") id ch02_sc05_014

    # ch02_sc05_dir007
    $ ch02_audio_stop("music")
    $ ch02_audio_stop("ch_ambience")
    window hide None
    scene ch02_bg theatre_exterior
    with fade
    show ch_qixing troubled at ch_left
    with dissolve
    $ ch_audio("street_room")

    # ch02_sc05_015
    window show None
    $ ch_line_id = "ch02_sc05_015"
    $ ch_voice(None, "ch02_sc05_015")
    ch_thought "……要去哪。打算上哪儿找。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}……どこへ行く。どこを捜すつもりだ。{/font}{/color}{/size}") id ch02_sc05_015

    # ch02_sc05_016
    window show None
    $ ch_line_id = "ch02_sc05_016"
    $ ch_voice(None, "ch02_sc05_016")
    ch_thought "她可能会去的地方，我哪怕知道一个吗？" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}あの子が行きそうな場所を、一つでも知ってるのか？{/font}{/color}{/size}") id ch02_sc05_016

    # ch02_sc05_017
    window show None
    $ ch_line_id = "ch02_sc05_017"
    $ ch_voice(None, "ch02_sc05_017")
    ch_thought "根本就一无所知啊。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}何も、知らないじゃないか。{/font}{/color}{/size}") id ch02_sc05_017

    # ch02_sc05_dir008
    window hide None
    pause 0.8
    $ ch02_audio_end()

    return
