# Generated by tools/build_ch02.py; JA SHA256 fa06b84c2245e33152c419fa7fc3abf503dc6ca34fde0aa2f9403a7f53730e0a
# ZH SHA256 bbaf5c62ea7d38647accaf1bc5308ecd390da01763d31cea280a8acd8447c52e
# Approved visual staging and audio; supplied voices are optional.
label ch02_sc06:
    $ ch02_audio_scene("ch02_sc06")

    # ch02_sc06_dir001
    call ch_card("ch02_chinatsu_home") from ch02_chinatsu_home_return
    window hide None
    scene ch02_cg chinatsu_limo_interior_v2
    with fade
    $ ch02_audio("car")
    $ ch02_audio("mystery_dark")

    # ch02_sc06_001
    window show None
    $ ch_line_id = "ch02_sc06_001"
    $ ch_voice('house_driver', "ch02_sc06_001")
    ch02_house_driver "梅川小姐，擅自离家，实在是太轻率了。您知道令尊有多担心吗。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}{rb}梅川{/rb}{rt}うめかわ{/rt}様。勝手に家をお出になるとは、あまりにも軽率です。お父様がどれほど心配なさったか。{/font}{/color}{/size}") id ch02_sc06_001

    # ch02_sc06_dir002
    $ ch02_audio_stop("ch_ambience", 0.8)
    window hide None
    scene ch02_cg limo_arrival_umekawa_v1
    with dissolve
    pause 0.9
    window hide None
    $ ch02_audio("mansion_open")
    scene ch02_bg foyer
    with dissolve
    show ch_chinatsu downcast at ch_right
    with dissolve
    $ ch02_audio("room")

    # ch02_sc06_002
    window show None
    $ ch_line_id = "ch02_sc06_002"
    $ ch_voice('beidai', "ch02_sc06_002")
    ch_beidai "哎呀，回来啦！爸爸的宝贝女儿回来了！" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}やあ、お帰り！　パパの大事な娘が帰ってきた！{/font}{/color}{/size}") id ch02_sc06_002

    # ch02_sc06_dir003
    window hide None
    scene ch02_cg beidai_welcome_chinatsu_v2
    with dissolve

    # ch02_sc06_003
    window show None
    $ ch_line_id = "ch02_sc06_003"
    $ ch_voice('beidai', "ch02_sc06_003")
    ch_beidai "带千夏去洗个澡，给她换身漂亮的衣服。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}千夏をお風呂に入れて、きれいな服に着替えさせてあげて。{/font}{/color}{/size}") id ch02_sc06_003

    # ch02_sc06_004
    window show None
    $ ch_line_id = "ch02_sc06_004"
    $ ch_voice('beidai', "ch02_sc06_004")
    ch_beidai "千夏，休息一会儿就来琴房。我们两个人聊聊天，好吗？" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}ねえ、千夏。少し休んだらピアノの部屋へおいで。二人でお話ししよう。いいね？{/font}{/color}{/size}") id ch02_sc06_004

    # ch02_sc06_dir004
    window hide None
    scene ch02_cg chinatsu_corridor_escort_v3
    with dissolve

    # ch02_sc06_005
    window show None
    $ ch_line_id = "ch02_sc06_005"
    $ ch_voice(None, "ch02_sc06_005")
    ch_thought "这里的淤青，明明才刚开始消下去。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}ここのあざ、やっと消えてきたところなのに。{/font}{/color}{/size}") id ch02_sc06_005

    # ch02_sc06_006
    window show None
    $ ch_line_id = "ch02_sc06_006"
    $ ch_voice(None, "ch02_sc06_006")
    ch_thought "不过两天没回来。地板、墙壁，什么都没变。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}二日、帰らなかっただけ。床も、壁も、何も変わっていない。{/font}{/color}{/size}") id ch02_sc06_006

    # ch02_sc06_007
    window show None
    $ ch_line_id = "ch02_sc06_007"
    $ ch_voice(None, "ch02_sc06_007")
    ch_thought "明明走过那么多遍，这条走廊却像个陌生的地方。……不。我认得这里。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}何度も通った廊下なのに、知らない場所みたい。……ううん。知ってる。ここは。{/font}{/color}{/size}") id ch02_sc06_007

    # ch02_sc06_008
    window show None
    $ ch_line_id = "ch02_sc06_008"
    $ ch_voice(None, "ch02_sc06_008")
    ch_thought "已经逃不掉了。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}もう、逃げられない。{/font}{/color}{/size}") id ch02_sc06_008

    # ch02_sc06_dir005
    window hide None
    pause 0.3

    # ch02_sc06_009
    window show None
    $ ch_line_id = "ch02_sc06_009"
    $ ch_voice(None, "ch02_sc06_009")
    ch_thought "好像从梦里醒过来了一样。真想在那个梦里，再多待一会儿。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}夢から、覚めてしまったみたい。もう少しだけ、あの中にいたかった。{/font}{/color}{/size}") id ch02_sc06_009

    # ch02_sc06_dir006
    window hide None
    scene ch02_cg restaurant_memory
    with Dissolve(0.6)

    # ch02_sc06_010
    window show None
    $ ch_line_id = "ch02_sc06_010"
    $ ch_voice(None, "ch02_sc06_010")
    ch_thought "那家店的饭菜，真好吃啊。椅子坐着也很舒服。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}あのお店のごはん、おいしかったな。椅子も、座り心地がよくて。{/font}{/color}{/size}") id ch02_sc06_010

    # ch02_sc06_011
    window show None
    $ ch_line_id = "ch02_sc06_011"
    $ ch_voice(None, "ch02_sc06_011")
    ch_thought "还有，那个人……" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}それから、あの人……。{/font}{/color}{/size}") id ch02_sc06_011

    # ch02_sc06_012
    window show None
    $ ch_line_id = "ch02_sc06_012"
    $ ch_voice(None, "ch02_sc06_012")
    ch_thought "要是一开始遇到的是警察，应该早就被带回家了吧。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}最初に会ったのがおまわりさんなら、もっと早く家に連れ戻されてたんだろうな。{/font}{/color}{/size}") id ch02_sc06_012

    # ch02_sc06_013
    window show None
    $ ch_line_id = "ch02_sc06_013"
    $ ch_voice(None, "ch02_sc06_013")
    ch_thought "那样说不定还好一些。如果从来都不知道，也就不用想着回到那里了。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}そのほうが、よかったのかもしれない。知らなければ、あそこに戻りたいなんて思わずに済んだのに。{/font}{/color}{/size}") id ch02_sc06_013

    # ch02_sc06_014
    window show None
    $ ch_line_id = "ch02_sc06_014"
    $ ch_voice(None, "ch02_sc06_014")
    ch_thought "可是，那个人不一样。他才不是什么警察。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}でも、あの人は違う。おまわりさんなんかじゃ、ない。{/font}{/color}{/size}") id ch02_sc06_014

    # ch02_sc06_dir007
    window hide None
    scene ch02_bg bathroom
    with dissolve
    $ ch02_audio("shower")

    # ch02_sc06_015
    window show None
    $ ch_line_id = "ch02_sc06_015"
    $ ch_voice(None, "ch02_sc06_015")
    ch_thought "……好痛。有些地方，只是碰到热水，还是会疼。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}……痛い。お湯が触れるだけで、まだ痛むところがある。{/font}{/color}{/size}") id ch02_sc06_015

    # ch02_sc06_016
    window show None
    $ ch_line_id = "ch02_sc06_016"
    $ ch_voice(None, "ch02_sc06_016")
    ch_thought "现在是二月，还能用羽绒服遮住。可就算到了夏天，也只有我还穿着长袖长裤。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}今は二月だから、ダウンで隠せる。でも、夏になっても、私だけ長袖と長いズボンのまま。{/font}{/color}{/size}") id ch02_sc06_016

    # ch02_sc06_017
    window show None
    $ ch_line_id = "ch02_sc06_017"
    $ ch_voice(None, "ch02_sc06_017")
    ch_thought "大家都在议论，说我很奇怪。明明谁都不知道为什么。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}みんな、変だって噂する。どうしてなのか、誰も知らないくせに。{/font}{/color}{/size}") id ch02_sc06_017

    # ch02_sc06_dir008
    pass

    # ch02_sc06_018
    window show None
    $ ch_line_id = "ch02_sc06_018"
    $ ch_voice('chinatsu', "ch02_sc06_018")
    ch_chinatsu "谁来……求求你。救救我……" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}誰か……お願い。助けて……。{/font}{/color}{/size}") id ch02_sc06_018

    # ch02_sc06_dir009
    $ ch02_audio_end(keep_music=True)
    window hide None
    scene black
    with fade

    return
