# Generated by tools/build_ch02.py; JA SHA256 fa06b84c2245e33152c419fa7fc3abf503dc6ca34fde0aa2f9403a7f53730e0a
# ZH SHA256 bbaf5c62ea7d38647accaf1bc5308ecd390da01763d31cea280a8acd8447c52e
# Approved visual staging and audio; supplied voices are optional.
label ch02_sc07:
    $ ch02_audio_scene("ch02_sc07")

    # ch02_sc07_dir001
    call ch_card("ch02_chinatsu_piano") from ch02_chinatsu_piano_return
    window hide None
    $ ch02_audio("mansion_open")
    scene ch02_bg piano
    show ch02_beidai home at ch_left
    with Dissolve(0.5)
    $ ch02_audio("room")
    pause 2.1
    $ ch02_audio("heels")
    $ renpy.pause(2.92, hard=True)
    show ch02_chinatsu dress at ch_right
    with Dissolve(0.35)

    # ch02_sc07_001
    window show None
    $ ch_line_id = "ch02_sc07_001"
    $ ch_voice(None, "ch02_sc07_001")
    ch_thought "明明是在家里。可每次进这个房间，都必须穿礼服。……为什么非得这样。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}家の中なのに。この部屋に入るときは、必ずドレス。……どうして、そこまで。{/font}{/color}{/size}") id ch02_sc07_001

    # ch02_sc07_dir002
    show ch02_beidai home_tender at ch_left
    with Dissolve(0.2)

    # ch02_sc07_002
    window show None
    $ ch_line_id = "ch02_sc07_002"
    $ ch_voice('beidai', "ch02_sc07_002")
    ch_beidai "千夏，到爸爸身边来。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}千夏。パパのそばへおいで。{/font}{/color}{/size}") id ch02_sc07_002

    # ch02_sc07_003
    window show None
    $ ch_line_id = "ch02_sc07_003"
    $ ch_voice(None, "ch02_sc07_003")
    ch_thought "……他在笑。带着那副笑容，看着我。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}……笑ってる。あの顔で、こっちを見てる。{/font}{/color}{/size}") id ch02_sc07_003

    # ch02_sc07_dir003
    pass
    hide ch02_chinatsu
    hide ch02_beidai
    with dissolve

    # ch02_sc07_004
    window show None
    $ ch_line_id = "ch02_sc07_004"
    $ ch_voice('beidai', "ch02_sc07_004")
    ch_beidai "让爸爸好好看看你的脸。在外面这段时间，是不是都瘦了？" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}顔をよく見せてごらん。外にいた間に、痩せてしまったんじゃないかい？{/font}{/color}{/size}") id ch02_sc07_004

    # ch02_sc07_dir004
    window hide None
    scene ch02_cg piano_forced_turn_v1
    with dissolve

    # ch02_sc07_005
    window show None
    $ ch_line_id = "ch02_sc07_005"
    $ ch_voice('beidai', "ch02_sc07_005")
    ch_beidai "果然瘦了好多。一定吃了不少苦吧。下次要乖乖的，不许再瞒着爸爸逃走了。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}やっぱり、ずいぶん痩せた。ひどい目に遭ったんだろう。次はいい子にして、パパに黙って逃げたりしないこと。{/font}{/color}{/size}") id ch02_sc07_005

    # ch02_sc07_006
    window show None
    $ ch_line_id = "ch02_sc07_006"
    $ ch_voice(None, "ch02_sc07_006")
    ch_thought "那种声音。净说些温柔的话……真恶心。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}その声。優しい言葉ばかり並べて……気持ちが悪い。{/font}{/color}{/size}") id ch02_sc07_006

    # ch02_sc07_dir005
    window hide None
    scene ch02_cg piano_push_away_v1
    with dissolve

    # ch02_sc07_007
    window show None
    $ ch_line_id = "ch02_sc07_007"
    $ ch_voice('chinatsu', "ch02_sc07_007")
    ch_chinatsu "爸爸，请您住手！" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}お父さん、やめてください！{/font}{/color}{/size}") id ch02_sc07_007

    # ch02_sc07_008
    window show None
    $ ch_line_id = "ch02_sc07_008"
    $ ch_voice('beidai', "ch02_sc07_008")
    ch_beidai "生什么气。你是我的女人，稍微摸一下又怎么了。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}何を怒ってるんだい。お前は俺の女だろう。少しくらい触ったっていいじゃないか。{/font}{/color}{/size}") id ch02_sc07_008

    # ch02_sc07_009
    window show None
    $ ch_line_id = "ch02_sc07_009"
    $ ch_voice('chinatsu', "ch02_sc07_009")
    ch_chinatsu "我才不是你的女人！别再对我——" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}私は、あなたの女なんかじゃない！　もう、私に――{/font}{/color}{/size}") id ch02_sc07_009

    # ch02_sc07_dir006
    window hide None
    scene ch02_cg empty_keys
    with Dissolve(0.15)

    # ch02_sc07_010
    window show None
    $ ch_line_id = "ch02_sc07_010"
    $ ch_voice(None, "ch02_sc07_010")
    ch_thought "明明已经说了不要。却还是被他强吻了。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}嫌だと言ったのに。無理やり、キスをされた。{/font}{/color}{/size}") id ch02_sc07_010

    # ch02_sc07_dir007
    window hide None
    scene ch02_bg piano
    with dissolve
    show ch02_chinatsu dress_angry at ch_right
    show ch02_beidai disheveled_furious at ch_left
    with dissolve

    # ch02_sc07_011
    window show None
    $ ch_line_id = "ch02_sc07_011"
    $ ch_voice('beidai', "ch02_sc07_011")
    ch_beidai "你以为是谁给了你这条命！连你妈都是被你害死的！" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}誰がお前に命をやったと思ってる！　母親だって、お前のせいで死んだんだぞ！{/font}{/color}{/size}") id ch02_sc07_011

    # ch02_sc07_012
    window show None
    $ ch_line_id = "ch02_sc07_012"
    $ ch_voice('beidai', "ch02_sc07_012")
    ch_beidai "都这样了，还敢说你不是我的！" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}それでも、俺のものじゃないと言うのか！{/font}{/color}{/size}") id ch02_sc07_012

    # ch02_sc07_dir008
    pause 0.25

    # ch02_sc07_013
    window show None
    $ ch_line_id = "ch02_sc07_013"
    $ ch_voice(None, "ch02_sc07_013")
    ch_thought "火……妈妈的手臂。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}火が……。お母さんの、腕。{/font}{/color}{/size}") id ch02_sc07_013

    # ch02_sc07_dir009
    window hide None
    scene ch02_cg memory_flames_v1
    with Dissolve(0.6)
    show ch02_memory_arm at ch02_memory_sway
    with Dissolve(0.4)

    # ch02_sc07_014
    window show None
    $ ch_line_id = "ch02_sc07_014"
    $ ch_voice(None, "ch02_sc07_014")
    ch_thought "那时的话，一直在脑子里挥之不去。不要……" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}あのときの言葉が、頭から離れない。やめて……。{/font}{/color}{/size}") id ch02_sc07_014

    # ch02_sc07_dir010
    window hide None
    scene ch02_cg chinatsu_piano_stand_fear_v1
    with Dissolve(0.25)

    # ch02_sc07_015
    window show None
    $ ch_line_id = "ch02_sc07_015"
    $ ch_voice('chinatsu', "ch02_sc07_015")
    ch_chinatsu "不是……不是。不是我……" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}違う……違う。私じゃ、ない……。{/font}{/color}{/size}") id ch02_sc07_015

    # ch02_sc07_dir011
    $ ch02_audio_end(keep_music=True)
    window hide None
    scene black
    with fade

    return
