# Generated by tools/build_ch02.py; JA SHA256 fa06b84c2245e33152c419fa7fc3abf503dc6ca34fde0aa2f9403a7f53730e0a
# ZH SHA256 bbaf5c62ea7d38647accaf1bc5308ecd390da01763d31cea280a8acd8447c52e
# Approved visual staging and audio; supplied voices are optional.
label ch02_sc08:
    $ ch02_audio_scene("ch02_sc08")

    # ch02_sc08_dir001
    call ch_card("ch02_phone") from ch02_phone_return
    window hide None
    scene ch02_bg phone_dusk
    with dissolve
    show ch02_beidai disheveled_curt at ch02_phone_left
    show ch02_house_servant neutral at ch02_service_right
    with dissolve
    $ ch02_audio("room")

    # ch02_sc08_001
    window show None
    $ ch_line_id = "ch02_sc08_001"
    $ ch_voice('beidai', "ch02_sc08_001")
    ch_beidai "谁打来的？" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}誰からだ？{/font}{/color}{/size}") id ch02_sc08_001

    # ch02_sc08_002
    window show None
    $ ch_line_id = "ch02_sc08_002"
    $ ch_voice('house_servant', "ch02_sc08_002")
    ch02_house_servant "不清楚。对方只说，您听到声音就会明白。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}分かりません。声を聞けばお分かりになる、とだけ。{/font}{/color}{/size}") id ch02_sc08_002

    # ch02_sc08_dir002
    show ch02_house_servant neutral at ch02_servant_offer
    pause 0.25
    show ch02_beidai phone_polite at ch02_phone_left
    with Dissolve(0.25)

    # ch02_sc08_003
    window show None
    $ ch_line_id = "ch02_sc08_003"
    $ ch_voice('beidai', "ch02_sc08_003")
    ch_beidai "喂，您好。我是梅川备代，请问您是哪位？" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}もしもし。{rb}梅川備代{/rb}{rt}サスペンダーなし{/rt}ですが、どちら様でしょうか。{/font}{/color}{/size}") id ch02_sc08_003

    # ch02_sc08_dir003
    $ ch02_audio_stop("music", 0.6)
    window hide None
    pause 0.5
    show ch02_house_servant neutral at ch02_servant_exit
    pause 0.4
    hide ch02_house_servant
    $ ch02_audio("mansion_open")
    show ch02_beidai phone_uneasy at ch02_phone_left
    with Dissolve(0.2)
    pause 0.7

    # ch02_sc08_004
    window show None
    $ ch_line_id = "ch02_sc08_004"
    $ ch_voice('unknown_caller', "ch02_sc08_004")
    ch02_unknown_caller "梅川备代先生。时间过得，可真快啊。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}{rb}梅川備代{/rb}{rt}サスペンダーなし{/rt}さん。時がたつのは、本当に早いものですね。{/font}{/color}{/size}") id ch02_sc08_004

    # ch02_sc08_dir004
    show ch02_beidai phone_afraid at ch02_phone_recoil
    with Dissolve(0.15)
    pause 0.25

    # ch02_sc08_005
    window show None
    $ ch_line_id = "ch02_sc08_005"
    $ ch_voice('beidai', "ch02_sc08_005")
    ch_beidai "你、你……居然，还活着……？" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}お、お前……まだ、生きていたのか……？{/font}{/color}{/size}") id ch02_sc08_005

    # ch02_sc08_dir005
    $ ch02_audio_end()
    window hide None
    scene black
    with Dissolve(0.8)

    return
