# Generated by tools/build_ch02.py; JA SHA256 fa06b84c2245e33152c419fa7fc3abf503dc6ca34fde0aa2f9403a7f53730e0a
# ZH SHA256 bbaf5c62ea7d38647accaf1bc5308ecd390da01763d31cea280a8acd8447c52e
# Approved visual staging and audio; supplied voices are optional.
label ch02_sc09:
    $ ch02_audio_scene("ch02_sc09")

    # ch02_sc09_dir001
    call ch_card("ch02_qixing_night") from ch02_qixing_night_return
    window hide None
    scene ch02_bg night
    with dissolve
    show ch_qixing neutral at ch_left
    with dissolve
    $ ch02_audio("night")
    $ ch02_audio("mystery_low")

    # ch02_sc09_001
    window show None
    $ ch_line_id = "ch02_sc09_001"
    $ ch_voice(None, "ch02_sc09_001")
    ch_thought "音乐会早就结束了。马皙也已经回去了。我却还在这里走着。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}コンサートなんて、とっくに終わっている。馬皙も、もう帰った。俺は、まだここを歩いてる。{/font}{/color}{/size}") id ch02_sc09_001

    # ch02_sc09_002
    window show None
    $ ch_line_id = "ch02_sc09_002"
    $ ch_voice(None, "ch02_sc09_002")
    ch_qixing "岛田千夏……梅川千夏……" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}島田千夏……梅川千夏……。{/font}{/color}{/size}") id ch02_sc09_002

    # ch02_sc09_003
    window show None
    $ ch_line_id = "ch02_sc09_003"
    $ ch_voice(None, "ch02_sc09_003")
    ch_thought "到底发生了什么。她究竟在逃避什么。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}何があったんだ。何から、逃げていたんだろう。{/font}{/color}{/size}") id ch02_sc09_003

    # ch02_sc09_004
    window show None
    $ ch_line_id = "ch02_sc09_004"
    $ ch_voice(None, "ch02_sc09_004")
    ch_thought "……那些以后再想。得先找到她。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}……考えるのは後だ。まず、見つけないと。{/font}{/color}{/size}") id ch02_sc09_004

    # ch02_sc09_005
    window show None
    $ ch_line_id = "ch02_sc09_005"
    $ ch_voice(None, "ch02_sc09_005")
    ch_thought "如今连寻人启事都没了，也没法出动警力。只希望她已经平安回家了。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}尋ね人の張り紙までなくなった今、警察を動かすわけにもいかない。無事に家へ戻っていてくれれば、いいんだけど。{/font}{/color}{/size}") id ch02_sc09_005

    # ch02_sc09_dir002
    window hide None
    scene ch02_cg qixing_stargaze_side_v1
    with dissolve

    # ch02_sc09_006
    window show None
    $ ch_line_id = "ch02_sc09_006"
    $ ch_voice(None, "ch02_sc09_006")
    ch_thought "……星星，看得好清楚。这些形状，小时候在星图上见过。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}……星が、よく見える。子どもの頃、星図で見た形だ。{/font}{/color}{/size}") id ch02_sc09_006

    # ch02_sc09_007
    window show None
    $ ch_line_id = "ch02_sc09_007"
    $ ch_voice(None, "ch02_sc09_007")
    ch_thought "从小到大，也就记性还不错。二十岁就被当成老手，或许多少也有它的功劳。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}記憶力だけは、昔からよかった。二十歳でベテラン扱いされるのも、少しはそのおかげかもしれない。{/font}{/color}{/size}") id ch02_sc09_007

    # ch02_sc09_008
    window show None
    $ ch_line_id = "ch02_sc09_008"
    $ ch_voice(None, "ch02_sc09_008")
    ch_qixing "那是宝瓶座。那边是双鱼座。然后是，仙女座……？" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}あれが、みずがめ座。そっちが、うお座。それから、アンドロメダ座……？{/font}{/color}{/size}") id ch02_sc09_008

    # ch02_sc09_dir003
    window hide None
    scene ch02_bg sky
    with dissolve
    show ch02_star help

    # ch02_sc09_009
    window show None
    $ ch_line_id = "ch02_sc09_009"
    $ ch_voice(None, "ch02_sc09_009")
    ch_thought "只有那颗星不太对劲。刚才还一闪一闪的，这会儿却又亮了很久……" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}あの星だけ、妙だ。せわしなく光ったと思えば、今度は長く……。{/font}{/color}{/size}") id ch02_sc09_009

    # ch02_sc09_010
    window show None
    $ ch_line_id = "ch02_sc09_010"
    $ ch_voice(None, "ch02_sc09_010")
    ch_thought "短，长。停一下，又是短的。……摩尔斯电码？" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}短く、長く。間を置いて、また短く。……モールス信号？{/font}{/color}{/size}") id ch02_sc09_010

    # ch02_sc09_dir004
    show ch02_star help

    # ch02_sc09_011
    window show None
    $ ch_line_id = "ch02_sc09_011"
    $ ch_voice(None, "ch02_sc09_011")
    ch_thought "能读懂。摩尔斯电码，我懂。……冷静，一个一个来。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}読める。モールスなら、分かる。……落ち着け。ひとつずつだ。{/font}{/color}{/size}") id ch02_sc09_011

    # ch02_sc09_012
    window show None
    $ ch_line_id = "ch02_sc09_012"
    $ ch_voice(None, "ch02_sc09_012")
    ch_qixing "H……E……L……P……H……E……L……" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}H……E……L……P……。H……E……L……。{/font}{/color}{/size}") id ch02_sc09_012

    # ch02_sc09_013
    window show None
    $ ch_line_id = "ch02_sc09_013"
    $ ch_voice(None, "ch02_sc09_013")
    ch_thought "HELP。一直在重复同一个词。救命。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}HELP。同じ言葉を繰り返している。助けて、と。{/font}{/color}{/size}") id ch02_sc09_013

    # ch02_sc09_014
    window show None
    $ ch_line_id = "ch02_sc09_014"
    $ ch_voice(None, "ch02_sc09_014")
    ch_qixing "……梅川千夏。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}……梅川千夏。{/font}{/color}{/size}") id ch02_sc09_014

    # ch02_sc09_015
    window show None
    $ ch_line_id = "ch02_sc09_015"
    $ ch_voice(None, "ch02_sc09_015")
    ch_thought "不知为什么，脑海里浮现出了她的名字。心跳越来越快。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}なぜか、あの子の名前が浮かんだ。胸の鼓動が、速くなる。{/font}{/color}{/size}") id ch02_sc09_015

    # ch02_sc09_dir005
    hide ch02_star
    show ch02_star coordinates

    # ch02_sc09_016
    window show None
    $ ch_line_id = "ch02_sc09_016"
    $ ch_voice(None, "ch02_sc09_016")
    ch_thought "等等，变了。这次是——" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}待て。今、変わった。今度は――。{/font}{/color}{/size}") id ch02_sc09_016

    # ch02_sc09_017
    window show None
    $ ch_line_id = "ch02_sc09_017"
    $ ch_voice(None, "ch02_sc09_017")
    ch_qixing "8……9……N……6……4……W……" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}8……9……N……6……4……W……。{/font}{/color}{/size}") id ch02_sc09_017

    # ch02_sc09_018
    window show None
    $ ch_line_id = "ch02_sc09_018"
    $ ch_voice(None, "ch02_sc09_018")
    ch_thought "89°N，64°W。北纬八十九度，西经六十四度。……是坐标。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}89°N、64°W。北緯八十九度、西経六十四度。……座標だ。{/font}{/color}{/size}") id ch02_sc09_018

    # ch02_sc09_019
    window show None
    $ ch_line_id = "ch02_sc09_019"
    $ ch_voice(None, "ch02_sc09_019")
    ch_thought "也许，千夏正在那里求救。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}千夏が、そこで助けを求めているのかもしれない。{/font}{/color}{/size}") id ch02_sc09_019

    # ch02_sc09_020
    window show None
    $ ch_line_id = "ch02_sc09_020"
    $ ch_voice(None, "ch02_sc09_020")
    ch_thought "不，等等。北纬八十九度……那不是北极吗。她怎么会在那种地方？" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}いや、待てよ。北緯八十九度って……北極じゃないか。どうして、あの子がそんなところに？{/font}{/color}{/size}") id ch02_sc09_020

    # ch02_sc09_dir006
    hide ch02_star
    window hide None
    scene ch02_cg chinatsu_bruise_detail_v3
    with Dissolve(0.5)

    # ch02_sc09_021
    window show None
    $ ch_line_id = "ch02_sc09_021"
    $ ch_voice(None, "ch02_sc09_021")
    ch_thought "左臂上的那块淤青。刚一碰到，就立刻缩回去的手。" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}あの左腕の、あざ。触れた瞬間に、引っ込めた手。{/font}{/color}{/size}") id ch02_sc09_021

    # ch02_sc09_022
    window show None
    $ ch_line_id = "ch02_sc09_022"
    $ ch_voice(None, "ch02_sc09_022")
    ch_thought "远比我想的，还要……" (show_ja_text="{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}俺が考えていたより、ずっと……。{/font}{/color}{/size}") id ch02_sc09_022

    # ch02_sc09_dir007
    window hide None
    scene ch02_cg qixing_stargaze_side_v1
    with Dissolve(0.6)
    pause 0.7
    window hide None
    scene black
    with fade
    $ ch02_audio_end()
    call ch_card("ch02_ending") from ch02_ending_return

    return
