# Chapter 1 entry. Generated by tools/build_ch01.py.
label start:
    $ ch_chapter_label = "第一章"
    $ ch_stop_audio()
    call ch_card("ch01_title") from ch01_title_return
    call ch01_sc01 from entry_ch01_sc01_return
    call ch01_sc02 from entry_ch01_sc02_return
    call ch01_sc03 from entry_ch01_sc03_return
    call ch01_sc04 from entry_ch01_sc04_return
    call ch01_sc05 from entry_ch01_sc05_return
    call ch01_sc06 from entry_ch01_sc06_return
    $ ch_stop_audio()
    call ch02_start from entry_ch02_return
    return
