"""Build only Chapter 1 from validated Japanese source. Does not launch Ren'Py."""
from pathlib import Path
import hashlib
import json
import re
import runpy

ROOT = Path(__file__).resolve().parents[1]
for output_folder in ('.build/reports', '.build/exports'):
    (ROOT / output_folder).mkdir(parents=True, exist_ok=True)
exported = runpy.run_path(str(ROOT / 'tools/export_ch01.py'))
data = exported['data']
ruby = exported['ruby']
source_hash = hashlib.sha256(exported['source'].read_bytes()).hexdigest()
translation_path = ROOT / 'scripts/zh/ch01.json'
translation = json.loads(translation_path.read_text(encoding='utf-8-sig'))
assert translation['chapter_id'] == data['chapter_id']
assert translation['source_ja_sha256'].lower() == source_hash, 'Chinese translation needs Japanese source review'
expected_ids = {e['id'] for s in data['scenes'] for e in s['entries'] if e['type'] != 'direction'}
assert set(translation['lines']) == expected_ids, 'Missing or stale Chinese line IDs'
assert all(isinstance(t, str) and t.strip() and not any(c in t for c in '{}〖〗\n')
           for t in translation['lines'].values()), 'Chinese must be nonempty plain text'
translation_hash = hashlib.sha256(translation_path.read_bytes()).hexdigest()

staging_data = json.loads((ROOT / 'scripts/staging/ch01/directions.json').read_text(encoding='utf-8'))
staging = staging_data['directions']
before = staging_data['before']

destination = ROOT / 'game/scripts/ch01'
destination.mkdir(parents=True, exist_ok=True)
used = set()
all_lines = []
voice_lines = []
def quote(text):
    return json.dumps(text, ensure_ascii=False)

def stage_lines(commands):
    # Dialogue remains visible during pauses and expression changes. Hide it
    # only for an actual shot change or an explicit clean-image performance.
    result = []
    for command in commands:
        if command.startswith('scene '):
            result.append('    window hide None')
        result.append('    ' + command)
    return result

for scene in data['scenes']:
    lines = [f'# Generated from scripts/ja/ch01.yaml SHA256 {source_hash}',
             f'# Chinese source scripts/zh/ch01.json SHA256 {translation_hash}',
             '# Edit Japanese text in YAML; staging in scripts/staging/ch01/directions.json.', '',
             f"label {scene['id']}:"]
    for entry in scene['entries']:
        line_id = entry['id']
        lines += [f'    # {line_id}']
        if entry['type'] == 'direction':
            assert line_id in staging, f'Unhandled direction: {line_id}'
            used.add(line_id)
            lines += ['    $ ch_voice(None, "")']
            lines += stage_lines(staging[line_id])
        else:
            all_lines.append(line_id)
            lines += stage_lines(before.get(line_id, []))
            character = 'ch_thought' if entry['type'] == 'thought' else 'ch_' + entry['speaker']
            if entry.get('display_name') == '少女':
                character = 'ch_girl'
            voice = entry['speaker'] if entry['type'] == 'dialogue' else None
            if voice:
                voice_lines.append(line_id)
            text = entry['ja'].replace('[', '[[')
            text = ruby.sub(lambda m: '{rb}' + m[1] + '{/rb}{rt}' + m[2] + '{/rt}', text)
            assert not any(c in text for c in '〖〗｜'), line_id
            chinese = translation['lines'][line_id].replace('[', '[[')
            # Native what is Chinese in full; Japanese is a screen argument.
            # Ren'Py snapshots show arguments in each HistoryEntry for history.
            text = '{size=24}{color=#aebdce}{font=fonts/SourceHanSerifJP-Medium.otf}' + text + '{/font}{/color}{/size}'
            lines += ['    window show None', f'    $ ch_line_id = {quote(line_id)}',
                      f'    $ ch_voice({repr(voice)}, {quote(line_id)})',
                      f'    {character} {quote(chinese)} (show_ja_text={quote(text)}) id {line_id}']
        lines += ['']
    lines += ['    return', '']
    (destination / (scene['id'].split('_')[1] + '.rpy')).write_text('\n'.join(lines), encoding='utf-8')
reading = ['# 第一章：' + translation['chapter_title_zh'], '',
           '中文主字幕 / 日语副字幕。中文仅依据日语台本及译名指南制作；配音仍使用既有日语清单。', '',
           '日语源 SHA-256：`' + source_hash + '`', '',
           '中文源 SHA-256：`' + translation_hash + '`', '']
for scene in data['scenes']:
    reading += ['## ' + scene['id'], '']
    for entry in scene['entries']:
        if entry['type'] == 'direction':
            continue
        reading += ['### ' + entry['id'] + ' · ' + entry['speaker'], '',
                    translation['lines'][entry['id']], '', entry['ja'], '']
(ROOT / '.build/exports/ch01_bilingual_script.md').write_text('\n'.join(reading), encoding='utf-8')
assert used == set(staging), 'Staging contains a stale direction ID'
assert set(voice_lines) == {r['line_id'] for r in exported['rows']}
entrypoint = ['# Chapter 1 entry. Generated by tools/build_ch01.py.', 'label start:',
              '    $ ch_chapter_label = "第一章"',
              '    $ ch_stop_audio()', '    call ch_card("ch01_title") from ch01_title_return']
entrypoint += [f"    call {scene['id']} from entry_{scene['id']}_return" for scene in data['scenes']]
entrypoint += ['    $ ch_stop_audio()', '    call ch02_start from entry_ch02_return', '    return', '']
(ROOT / 'game/script.rpy').write_text('\n'.join(entrypoint), encoding='utf-8')
report = {'script_sha256': source_hash, 'scenes': len(data['scenes']), 'texts': len(all_lines),
          'translation_sha256': translation_hash, 'translated_lines': len(translation['lines']),
          'subtitle_order': ['zh_primary', 'ja_secondary'],
          'directions': len(used), 'voice_lines': len(voice_lines),
          'checks': ['all_directions_mapped', 'stable_say_ids', 'voice_manifest_match', 'ruby_conversion'],
          'runtime_tested': False, 'runtime_owner': 'user'}
(ROOT / '.build/reports/ch01_build_check.json').write_text(json.dumps(report, indent=2), encoding='utf-8')
print(json.dumps(report))
